#include "CodexGraphAuditLibrary.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphNode_Comment.h"
#include "EdGraphSchema_K2.h"
#include "Components/PrimitiveComponent.h"
#include "Engine/Blueprint.h"
#include "GameFramework/Actor.h"
#include "K2Node_CallFunction.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Logging/TokenizedMessage.h"

namespace
{
    FString Safe(const FString& Value)
    {
        return Value.Replace(TEXT("\r"), TEXT("\\r"))
            .Replace(TEXT("\n"), TEXT("\\n"))
            .Replace(TEXT("\t"), TEXT("\\t"));
    }

    void AppendGraph(FString& Output, UEdGraph* Graph)
    {
        if (!Graph)
        {
            return;
        }

        Output += FString::Printf(TEXT("\nGRAPH\t%s\n"), *Graph->GetName());
        for (UEdGraphNode* Node : Graph->Nodes)
        {
            if (!Node)
            {
                continue;
            }

            Output += FString::Printf(
                TEXT("NODE\t%s\t%s\t%s\n"),
                *Node->GetClass()->GetName(),
                *Node->GetName(),
                *Safe(Node->GetNodeTitle(ENodeTitleType::FullTitle).ToString()));

            for (UEdGraphPin* Pin : Node->Pins)
            {
                if (!Pin)
                {
                    continue;
                }

                FString Links;
                for (UEdGraphPin* Link : Pin->LinkedTo)
                {
                    if (!Link)
                    {
                        continue;
                    }
                    if (!Links.IsEmpty())
                    {
                        Links += TEXT(",");
                    }
                    Links += Link->GetOwningNode()->GetName();
                    Links += TEXT(".");
                    Links += Link->PinName.ToString();
                }

                Output += FString::Printf(
                    TEXT("PIN\t%s\t%s\t%s\t%s\t%s\t%s\n"),
                    Pin->Direction == EGPD_Input ? TEXT("IN") : TEXT("OUT"),
                    *Pin->PinName.ToString(),
                    *Pin->PinType.PinCategory.ToString(),
                    *Safe(Pin->DefaultValue),
                    *Safe(Pin->AutogeneratedDefaultValue),
                    *Links);
            }
        }
    }

    UEdGraphPin* FindPinByNameOrCategory(
        UEdGraphNode* Node,
        const TArray<FString>& Names,
        const EEdGraphPinDirection Direction,
        const FName Category = NAME_None)
    {
        if (!Node)
        {
            return nullptr;
        }

        for (UEdGraphPin* Pin : Node->Pins)
        {
            if (!Pin || Pin->Direction != Direction)
            {
                continue;
            }

            const FString PinName = Pin->PinName.ToString();
            for (const FString& Name : Names)
            {
                if (PinName.Equals(Name, ESearchCase::IgnoreCase))
                {
                    return Pin;
                }
            }
        }

        if (Category != NAME_None)
        {
            for (UEdGraphPin* Pin : Node->Pins)
            {
                if (Pin &&
                    Pin->Direction == Direction &&
                    Pin->PinType.PinCategory == Category)
                {
                    return Pin;
                }
            }
        }

        return nullptr;
    }

    bool NodeTitleContains(UEdGraphNode* Node, const FString& Text)
    {
        return Node &&
            Node->GetNodeTitle(ENodeTitleType::FullTitle)
                .ToString()
                .Contains(Text, ESearchCase::IgnoreCase);
    }

    UEdGraphNode* FindNodeByTitle(UEdGraph* Graph, const FString& Text)
    {
        if (!Graph)
        {
            return nullptr;
        }

        for (UEdGraphNode* Node : Graph->Nodes)
        {
            if (NodeTitleContains(Node, Text))
            {
                return Node;
            }
        }

        return nullptr;
    }

    UEdGraphPin* FindPinExact(
        UEdGraphNode* Node,
        const TCHAR* PinName,
        const EEdGraphPinDirection Direction)
    {
        if (!Node)
        {
            return nullptr;
        }

        for (UEdGraphPin* Pin : Node->Pins)
        {
            if (Pin &&
                Pin->Direction == Direction &&
                Pin->PinName == PinName)
            {
                return Pin;
            }
        }

        return nullptr;
    }

    UEdGraphPin* FindExecIn(UEdGraphNode* Node)
    {
        return FindPinExact(Node, TEXT("execute"), EGPD_Input);
    }

    UEdGraphPin* FindThenOut(UEdGraphNode* Node)
    {
        return FindPinExact(Node, TEXT("then"), EGPD_Output);
    }

    void LinkPins(UEdGraphPin* From, UEdGraphPin* To)
    {
        if (From && To && !From->LinkedTo.Contains(To))
        {
            From->MakeLinkTo(To);
        }
    }

    bool HasCodexDriftMarker(UEdGraph* Graph)
    {
        if (!Graph)
        {
            return false;
        }

        for (UEdGraphNode* Node : Graph->Nodes)
        {
            const UEdGraphNode_Comment* Comment =
                Cast<UEdGraphNode_Comment>(Node);
            if (Comment &&
                Comment->NodeComment.Contains(
                    TEXT("Codex Mario Kart Drift"),
                    ESearchCase::IgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    bool HasCommentContaining(UEdGraph* Graph, const FString& Text)
    {
        if (!Graph)
        {
            return false;
        }

        for (UEdGraphNode* Node : Graph->Nodes)
        {
            const UEdGraphNode_Comment* Comment =
                Cast<UEdGraphNode_Comment>(Node);
            if (Comment &&
                Comment->NodeComment.Contains(Text, ESearchCase::IgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    UEdGraphNode_Comment* AddComment(
        UEdGraph* Graph,
        const FString& Text,
        int32 X,
        int32 Y,
        int32 W,
        int32 H)
    {
        UEdGraphNode_Comment* Comment = NewObject<UEdGraphNode_Comment>(Graph);
        Graph->AddNode(Comment, true, false);
        Comment->NodePosX = X;
        Comment->NodePosY = Y;
        Comment->NodeWidth = W;
        Comment->NodeHeight = H;
        Comment->NodeComment = Text;
        return Comment;
    }

    UK2Node_CallFunction* AddCallNode(
        UEdGraph* Graph,
        UClass* FunctionOwner,
        FName FunctionName,
        int32 X,
        int32 Y)
    {
        UK2Node_CallFunction* Node = NewObject<UK2Node_CallFunction>(Graph);
        Graph->AddNode(Node, true, false);
        Node->NodePosX = X;
        Node->NodePosY = Y;
        Node->FunctionReference.SetExternalMember(FunctionName, FunctionOwner);
        Node->AllocateDefaultPins();
        return Node;
    }

    UK2Node_CallFunction* AddSelfCallNode(
        UEdGraph* Graph,
        FName FunctionName,
        int32 X,
        int32 Y)
    {
        UK2Node_CallFunction* Node = NewObject<UK2Node_CallFunction>(Graph);
        Graph->AddNode(Node, true, false);
        Node->NodePosX = X;
        Node->NodePosY = Y;
        Node->FunctionReference.SetSelfMember(FunctionName);
        Node->AllocateDefaultPins();
        return Node;
    }

    UK2Node_VariableGet* AddVariableGet(
        UEdGraph* Graph,
        FName VarName,
        int32 X,
        int32 Y)
    {
        UK2Node_VariableGet* Node = NewObject<UK2Node_VariableGet>(Graph);
        Graph->AddNode(Node, true, false);
        Node->NodePosX = X;
        Node->NodePosY = Y;
        Node->VariableReference.SetSelfMember(VarName);
        Node->AllocateDefaultPins();
        return Node;
    }

    UK2Node_VariableSet* AddVariableSet(
        UEdGraph* Graph,
        FName VarName,
        int32 X,
        int32 Y)
    {
        UK2Node_VariableSet* Node = NewObject<UK2Node_VariableSet>(Graph);
        Graph->AddNode(Node, true, false);
        Node->NodePosX = X;
        Node->NodePosY = Y;
        Node->VariableReference.SetSelfMember(VarName);
        Node->AllocateDefaultPins();
        return Node;
    }

    UK2Node_IfThenElse* AddBranch(UEdGraph* Graph, int32 X, int32 Y)
    {
        UK2Node_IfThenElse* Node = NewObject<UK2Node_IfThenElse>(Graph);
        Graph->AddNode(Node, true, false);
        Node->NodePosX = X;
        Node->NodePosY = Y;
        Node->AllocateDefaultPins();
        return Node;
    }

    void EnsureMemberVariable(
        UBlueprint* Blueprint,
        FName VarName,
        FName Category,
        bool& bChanged,
        FString& Report)
    {
        if (FBlueprintEditorUtils::FindNewVariableIndex(Blueprint, VarName)
            != INDEX_NONE)
        {
            Report += FString::Printf(TEXT("%s=present; "),
                *VarName.ToString());
            return;
        }

        FEdGraphPinType PinType;
        PinType.PinCategory = Category;
        if (Category == UEdGraphSchema_K2::PC_Real)
        {
            PinType.PinSubCategory = UEdGraphSchema_K2::PC_Double;
        }
        if (FBlueprintEditorUtils::AddMemberVariable(
                Blueprint, VarName, PinType))
        {
            bChanged = true;
            Report += FString::Printf(TEXT("%s=created; "),
                *VarName.ToString());
        }
        else
        {
            Report += FString::Printf(TEXT("%s=FAILED; "),
                *VarName.ToString());
        }
    }

    void SetBoolDefault(UEdGraphNode* Node, const TCHAR* PinName, bool bValue)
    {
        if (UEdGraphPin* Pin = FindPinExact(Node, PinName, EGPD_Input))
        {
            Pin->DefaultValue = bValue ? TEXT("true") : TEXT("false");
        }
    }

    void SetRealDefault(UEdGraphNode* Node, const TCHAR* PinName, const TCHAR* Value)
    {
        if (UEdGraphPin* Pin = FindPinExact(Node, PinName, EGPD_Input))
        {
            Pin->DefaultValue = Value;
        }
    }

    UEdGraphPin* FindVariableOutput(UEdGraphNode* Node, const TCHAR* VarName)
    {
        return FindPinExact(Node, VarName, EGPD_Output);
    }

    UEdGraphPin* FindVariableInput(UEdGraphNode* Node, const TCHAR* VarName)
    {
        return FindPinExact(Node, VarName, EGPD_Input);
    }

    UEdGraphNode* FindExecChainEnd(UEdGraphNode* StartNode)
    {
        UEdGraphNode* Node = StartNode;
        for (int32 Guard = 0; Node && Guard < 100; ++Guard)
        {
            UEdGraphPin* ThenPin = FindThenOut(Node);
            if (!ThenPin || ThenPin->LinkedTo.Num() == 0)
            {
                return Node;
            }

            Node = ThenPin->LinkedTo[0]->GetOwningNode();
        }

        return Node;
    }

    void InsertExecNodeAfter(UEdGraphNode* ExistingNode, UEdGraphNode* NewNode)
    {
        UEdGraphPin* ExistingThen = FindThenOut(ExistingNode);
        UEdGraphPin* NewExec = FindExecIn(NewNode);
        UEdGraphPin* NewThen = FindThenOut(NewNode);
        if (!ExistingThen || !NewExec)
        {
            return;
        }

        TArray<UEdGraphPin*> OldLinks = ExistingThen->LinkedTo;
        ExistingThen->BreakAllPinLinks();
        ExistingThen->MakeLinkTo(NewExec);

        if (NewThen)
        {
            for (UEdGraphPin* OldLink : OldLinks)
            {
                if (OldLink)
                {
                    NewThen->MakeLinkTo(OldLink);
                }
            }
        }
    }

    int32 EnsureBlueprintNodeGuids(UBlueprint* Blueprint)
    {
        if (!Blueprint)
        {
            return 0;
        }

        int32 FixedCount = 0;
        auto FixGraph = [&FixedCount](UEdGraph* Graph)
        {
            if (!Graph)
            {
                return;
            }

            for (UEdGraphNode* Node : Graph->Nodes)
            {
                if (Node && !Node->NodeGuid.IsValid())
                {
                    Node->Modify();
                    Node->CreateNewGuid();
                    ++FixedCount;
                }
            }
        };

        for (UEdGraph* Graph : Blueprint->UbergraphPages)
        {
            FixGraph(Graph);
        }
        for (UEdGraph* Graph : Blueprint->FunctionGraphs)
        {
            FixGraph(Graph);
        }

        if (FixedCount > 0)
        {
            FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
        }

        return FixedCount;
    }
}

FString UCodexGraphAuditLibrary::DumpWeek7Graphs()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Output;
    for (UEdGraph* Graph : Blueprint->FunctionGraphs)
    {
        if (Graph && (
            Graph->GetFName() == TEXT("ApplyForwardBoost") ||
            Graph->GetFName() == TEXT("ApplyExternalBoost") ||
            Graph->GetFName() == TEXT("ApplyHitImpulse")))
        {
            AppendGraph(Output, Graph);
        }
    }

    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        AppendGraph(Output, Graph);
    }

    return Output;
}

FString UCodexGraphAuditLibrary::FixWeek7HitImpulseBalance()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;
    bool bForceLinked = false;
    bool bVelChangeDisabled = false;
    bool bDebugForceAdjusted = false;
    bool bDebugDirectionAdjusted = false;

    for (UEdGraph* Graph : Blueprint->FunctionGraphs)
    {
        if (!Graph || Graph->GetFName() != TEXT("ApplyHitImpulse"))
        {
            continue;
        }

        UEdGraphNode* EntryNode = FindNodeByTitle(Graph, TEXT("ApplyHitImpulse"));
        UEdGraphNode* MultiplyNode = FindNodeByTitle(Graph, TEXT("vector * vector"));
        UEdGraphNode* AddImpulseNode = FindNodeByTitle(Graph, TEXT("Add Impulse"));

        UEdGraphPin* ForcePin = FindPinByNameOrCategory(
            EntryNode,
            {TEXT("Force"), TEXT("Boost Force")},
            EGPD_Output,
            TEXT("real"));
        UEdGraphPin* MultiplyForcePin = FindPinByNameOrCategory(
            MultiplyNode,
            {TEXT("B")},
            EGPD_Input,
            TEXT("real"));
        UEdGraphPin* VelChangePin = FindPinByNameOrCategory(
            AddImpulseNode,
            {TEXT("bVelChange")},
            EGPD_Input);

        if (ForcePin && MultiplyForcePin &&
            (MultiplyForcePin->LinkedTo.Num() != 1 ||
             MultiplyForcePin->LinkedTo[0] != ForcePin))
        {
            MultiplyForcePin->Modify();
            ForcePin->Modify();
            MultiplyForcePin->BreakAllPinLinks();
            ForcePin->MakeLinkTo(MultiplyForcePin);
            bForceLinked = true;
            bChanged = true;
        }

        if (VelChangePin && !VelChangePin->DefaultValue.Equals(TEXT("false")))
        {
            VelChangePin->Modify();
            VelChangePin->DefaultValue = TEXT("false");
            bVelChangeDisabled = true;
            bChanged = true;
        }

        Graph->NotifyGraphChanged();
    }

    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (!Graph)
        {
            continue;
        }

        for (UEdGraphNode* Node : Graph->Nodes)
        {
            if (!NodeTitleContains(Node, TEXT("Apply Hit Impulse")))
            {
                continue;
            }

            UEdGraphPin* DebugForcePin = FindPinByNameOrCategory(
                Node,
                {TEXT("Force"), TEXT("Boost Force")},
                EGPD_Input,
                TEXT("real"));
            UEdGraphPin* DebugDirectionPin = FindPinByNameOrCategory(
                Node,
                {TEXT("Direction")},
                EGPD_Input);

            if (DebugForcePin &&
                !DebugForcePin->DefaultValue.Equals(TEXT("225000.000000")))
            {
                DebugForcePin->Modify();
                DebugForcePin->DefaultValue = TEXT("225000.000000");
                bDebugForceAdjusted = true;
                bChanged = true;
            }

            if (DebugDirectionPin &&
                !DebugDirectionPin->DefaultValue.Equals(
                    TEXT("0.000000,1.000000,0.150000")))
            {
                DebugDirectionPin->Modify();
                DebugDirectionPin->DefaultValue =
                    TEXT("0.000000,1.000000,0.150000");
                bDebugDirectionAdjusted = true;
                bChanged = true;
            }
        }

        Graph->NotifyGraphChanged();
    }

    if (bChanged)
    {
        FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    }

    Report += FString::Printf(
        TEXT("Changed=%s; ForceLinked=%s; bVelChangeDisabled=%s; DebugForce=225000; DebugDirection=0,1,0.15"),
        bChanged ? TEXT("true") : TEXT("false"),
        bForceLinked ? TEXT("true") : TEXT("false"),
        bVelChangeDisabled ? TEXT("true") : TEXT("false"));
    Report += FString::Printf(
        TEXT("; DebugForceAdjusted=%s; DebugDirectionAdjusted=%s"),
        bDebugForceAdjusted ? TEXT("true") : TEXT("false"),
        bDebugDirectionAdjusted ? TEXT("true") : TEXT("false"));

    return Report;
}

FString UCodexGraphAuditLibrary::ApplyMarioKartDriftMiniTurbo()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;

    EnsureMemberVariable(Blueprint, TEXT("bIsDrifting"),
        UEdGraphSchema_K2::PC_Boolean, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftCharge"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftChargeRate"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("MiniTurboThreshold"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("MiniTurboForce"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("bMiniTurboReady"),
        UEdGraphSchema_K2::PC_Boolean, bChanged, Report);

    for (UEdGraph* Graph : Blueprint->FunctionGraphs)
    {
        if (Graph && Graph->GetFName() == TEXT("ApplyForwardBoost"))
        {
            UEdGraphNode* EntryNode =
                FindNodeByTitle(Graph, TEXT("ApplyForwardBoost"));
            UEdGraphNode* MultiplyNode =
                FindNodeByTitle(Graph, TEXT("vector * vector"));
            UEdGraphPin* ForcePin = FindPinByNameOrCategory(
                EntryNode,
                {TEXT("Force"), TEXT("Boost Force")},
                EGPD_Output,
                TEXT("real"));
            UEdGraphPin* MultiplyForcePin = FindPinByNameOrCategory(
                MultiplyNode,
                {TEXT("B")},
                EGPD_Input,
                TEXT("real"));

            if (ForcePin && MultiplyForcePin &&
                (MultiplyForcePin->LinkedTo.Num() != 1 ||
                 MultiplyForcePin->LinkedTo[0] != ForcePin))
            {
                MultiplyForcePin->Modify();
                ForcePin->Modify();
                MultiplyForcePin->BreakAllPinLinks();
                ForcePin->MakeLinkTo(MultiplyForcePin);
                bChanged = true;
                Report += TEXT("ApplyForwardBoostUsesForce=true; ");
            }
        }
    }

    UEdGraph* EventGraph = nullptr;
    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (Graph && Graph->GetFName() == TEXT("EventGraph"))
        {
            EventGraph = Graph;
            break;
        }
    }

    if (!EventGraph)
    {
        return Report + TEXT("ERROR=EventGraph missing; ");
    }

    if (HasCodexDriftMarker(EventGraph))
    {
        return Report + TEXT("DriftGraph=already_present; ");
    }

    UEdGraphNode* HandbrakeNode =
        FindNodeByTitle(EventGraph, TEXT("IA_Handbrake"));
    if (!HandbrakeNode)
    {
        return Report + TEXT("ERROR=IA_Handbrake node missing; ");
    }

    UEdGraphNode* StartedSetHandbrake = nullptr;
    UEdGraphNode* CompletedSetHandbrake = nullptr;
    for (UEdGraphNode* Node : EventGraph->Nodes)
    {
        if (!NodeTitleContains(Node, TEXT("Set Handbrake Input")))
        {
            continue;
        }

        UEdGraphPin* bNewHandbrake =
            FindPinExact(Node, TEXT("bNewHandbrake"), EGPD_Input);
        if (bNewHandbrake && bNewHandbrake->LinkedTo.Num() > 0)
        {
            StartedSetHandbrake = Node;
        }
        else if (bNewHandbrake)
        {
            CompletedSetHandbrake = Node;
        }
    }

    if (!StartedSetHandbrake || !CompletedSetHandbrake)
    {
        return Report + TEXT("ERROR=SetHandbrake nodes missing; ");
    }

    EventGraph->Modify();
    AddComment(
        EventGraph,
        TEXT("Codex Mario Kart Drift - IA_Handbrake: hop, charge, mini-turbo"),
        1700, -850, 1900, 950);

    // Start drift after the existing handbrake press path.
    UK2Node_CallFunction* TryJump =
        AddSelfCallNode(EventGraph, TEXT("TryJump"), 1750, -660);
    UK2Node_VariableSet* SetIsDrifting =
        AddVariableSet(EventGraph, TEXT("bIsDrifting"), 1970, -660);
    SetBoolDefault(SetIsDrifting, TEXT("bIsDrifting"), true);
    UK2Node_VariableSet* ResetCharge =
        AddVariableSet(EventGraph, TEXT("DriftCharge"), 2190, -660);
    SetRealDefault(ResetCharge, TEXT("DriftCharge"), TEXT("0.000000"));
    UK2Node_VariableSet* ResetReady =
        AddVariableSet(EventGraph, TEXT("bMiniTurboReady"), 2410, -660);
    SetBoolDefault(ResetReady, TEXT("bMiniTurboReady"), false);
    UK2Node_CallFunction* PrintStart = AddCallNode(
        EventGraph,
        UKismetSystemLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, PrintString),
        2630, -660);
    SetRealDefault(PrintStart, TEXT("Duration"), TEXT("1.000000"));
    if (UEdGraphPin* InString =
            FindPinExact(PrintStart, TEXT("InString"), EGPD_Input))
    {
        InString->DefaultValue = TEXT("DRIFT START");
    }
    if (UEdGraphPin* Key =
            FindPinExact(PrintStart, TEXT("Key"), EGPD_Input))
    {
        Key->DefaultValue = TEXT("DRIFT");
    }

    LinkPins(FindThenOut(StartedSetHandbrake), FindExecIn(TryJump));
    LinkPins(FindThenOut(TryJump), FindExecIn(SetIsDrifting));
    LinkPins(FindThenOut(SetIsDrifting), FindExecIn(ResetCharge));
    LinkPins(FindThenOut(ResetCharge), FindExecIn(ResetReady));
    LinkPins(FindThenOut(ResetReady), FindExecIn(PrintStart));

    // Charge drift from IA_Handbrake TriggeredSeconds.
    UK2Node_IfThenElse* ChargeBranch = AddBranch(EventGraph, 1750, -330);
    UK2Node_VariableGet* GetIsDrifting =
        AddVariableGet(EventGraph, TEXT("bIsDrifting"), 1530, -210);
    UK2Node_VariableGet* GetChargeRate =
        AddVariableGet(EventGraph, TEXT("DriftChargeRate"), 1750, -110);
    UK2Node_CallFunction* MultiplyCharge = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        1970, -170);
    UK2Node_VariableSet* SetDriftCharge =
        AddVariableSet(EventGraph, TEXT("DriftCharge"), 2190, -330);
    UK2Node_VariableGet* GetThreshold =
        AddVariableGet(EventGraph, TEXT("MiniTurboThreshold"), 2190, -80);
    UK2Node_CallFunction* ChargeReadyCompare = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, GreaterEqual_DoubleDouble),
        2410, -250);
    UK2Node_IfThenElse* ReadyBranch = AddBranch(EventGraph, 2630, -330);
    UK2Node_VariableSet* SetReady =
        AddVariableSet(EventGraph, TEXT("bMiniTurboReady"), 2850, -330);
    SetBoolDefault(SetReady, TEXT("bMiniTurboReady"), true);
    UK2Node_CallFunction* PrintReady = AddCallNode(
        EventGraph,
        UKismetSystemLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, PrintString),
        3070, -330);
    SetRealDefault(PrintReady, TEXT("Duration"), TEXT("0.200000"));
    if (UEdGraphPin* InString =
            FindPinExact(PrintReady, TEXT("InString"), EGPD_Input))
    {
        InString->DefaultValue = TEXT("MINI TURBO READY");
    }
    if (UEdGraphPin* Key =
            FindPinExact(PrintReady, TEXT("Key"), EGPD_Input))
    {
        Key->DefaultValue = TEXT("DRIFT");
    }

    LinkPins(
        FindPinExact(HandbrakeNode, TEXT("Triggered"), EGPD_Output),
        FindExecIn(ChargeBranch));
    LinkPins(
        FindVariableOutput(GetIsDrifting, TEXT("bIsDrifting")),
        FindPinExact(ChargeBranch, TEXT("Condition"), EGPD_Input));
    LinkPins(
        FindPinExact(ChargeBranch, TEXT("then"), EGPD_Output),
        FindExecIn(SetDriftCharge));
    LinkPins(
        FindPinExact(HandbrakeNode, TEXT("TriggeredSeconds"), EGPD_Output),
        FindPinExact(MultiplyCharge, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetChargeRate, TEXT("DriftChargeRate")),
        FindPinExact(MultiplyCharge, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(MultiplyCharge, TEXT("ReturnValue"), EGPD_Output),
        FindVariableInput(SetDriftCharge, TEXT("DriftCharge")));
    LinkPins(FindThenOut(SetDriftCharge), FindExecIn(ReadyBranch));
    LinkPins(
        FindVariableOutput(SetDriftCharge, TEXT("Output_Get")),
        FindPinExact(ChargeReadyCompare, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetThreshold, TEXT("MiniTurboThreshold")),
        FindPinExact(ChargeReadyCompare, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(ChargeReadyCompare, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(ReadyBranch, TEXT("Condition"), EGPD_Input));
    LinkPins(
        FindPinExact(ReadyBranch, TEXT("then"), EGPD_Output),
        FindExecIn(SetReady));
    LinkPins(FindThenOut(SetReady), FindExecIn(PrintReady));

    // End drift: if mini-turbo is ready, call ApplyForwardBoost, then reset.
    UK2Node_VariableSet* EndSetDrifting =
        AddVariableSet(EventGraph, TEXT("bIsDrifting"), 1750, 20);
    SetBoolDefault(EndSetDrifting, TEXT("bIsDrifting"), false);
    UK2Node_VariableGet* GetReadyEnd =
        AddVariableGet(EventGraph, TEXT("bMiniTurboReady"), 1750, 170);
    UK2Node_IfThenElse* EndBranch = AddBranch(EventGraph, 1970, 20);
    UK2Node_CallFunction* ApplyBoost =
        AddSelfCallNode(EventGraph, TEXT("ApplyForwardBoost"), 2190, 20);
    UK2Node_VariableGet* GetMiniTurboForce =
        AddVariableGet(EventGraph, TEXT("MiniTurboForce"), 2190, 170);
    UK2Node_CallFunction* PrintBoost = AddCallNode(
        EventGraph,
        UKismetSystemLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, PrintString),
        2410, 20);
    SetRealDefault(PrintBoost, TEXT("Duration"), TEXT("1.000000"));
    if (UEdGraphPin* InString =
            FindPinExact(PrintBoost, TEXT("InString"), EGPD_Input))
    {
        InString->DefaultValue = TEXT("MINI TURBO!");
    }
    if (UEdGraphPin* Key =
            FindPinExact(PrintBoost, TEXT("Key"), EGPD_Input))
    {
        Key->DefaultValue = TEXT("DRIFT");
    }
    UK2Node_VariableSet* EndResetReadyA =
        AddVariableSet(EventGraph, TEXT("bMiniTurboReady"), 2630, 20);
    SetBoolDefault(EndResetReadyA, TEXT("bMiniTurboReady"), false);
    UK2Node_VariableSet* EndResetChargeA =
        AddVariableSet(EventGraph, TEXT("DriftCharge"), 2850, 20);
    SetRealDefault(EndResetChargeA, TEXT("DriftCharge"), TEXT("0.000000"));
    UK2Node_VariableSet* EndResetReadyB =
        AddVariableSet(EventGraph, TEXT("bMiniTurboReady"), 2190, 330);
    SetBoolDefault(EndResetReadyB, TEXT("bMiniTurboReady"), false);
    UK2Node_VariableSet* EndResetChargeB =
        AddVariableSet(EventGraph, TEXT("DriftCharge"), 2410, 330);
    SetRealDefault(EndResetChargeB, TEXT("DriftCharge"), TEXT("0.000000"));

    LinkPins(FindThenOut(CompletedSetHandbrake), FindExecIn(EndSetDrifting));
    LinkPins(FindThenOut(EndSetDrifting), FindExecIn(EndBranch));
    LinkPins(
        FindVariableOutput(GetReadyEnd, TEXT("bMiniTurboReady")),
        FindPinExact(EndBranch, TEXT("Condition"), EGPD_Input));
    LinkPins(
        FindPinExact(EndBranch, TEXT("then"), EGPD_Output),
        FindExecIn(ApplyBoost));
    LinkPins(
        FindVariableOutput(GetMiniTurboForce, TEXT("MiniTurboForce")),
        FindPinExact(ApplyBoost, TEXT("Boost Force"), EGPD_Input));
    LinkPins(FindThenOut(ApplyBoost), FindExecIn(PrintBoost));
    LinkPins(FindThenOut(PrintBoost), FindExecIn(EndResetReadyA));
    LinkPins(FindThenOut(EndResetReadyA), FindExecIn(EndResetChargeA));
    LinkPins(
        FindPinExact(EndBranch, TEXT("else"), EGPD_Output),
        FindExecIn(EndResetReadyB));
    LinkPins(FindThenOut(EndResetReadyB), FindExecIn(EndResetChargeB));

    EventGraph->NotifyGraphChanged();
    FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    bChanged = true;

    return Report + FString::Printf(
        TEXT("DriftGraph=created; Changed=%s; "),
        bChanged ? TEXT("true") : TEXT("false"));
}

FString UCodexGraphAuditLibrary::FixMarioKartDriftRuntimeFeel()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;

    EnsureMemberVariable(Blueprint, TEXT("bIsDrifting"),
        UEdGraphSchema_K2::PC_Boolean, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftCharge"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftChargeRate"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("MiniTurboThreshold"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("MiniTurboForce"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("bMiniTurboReady"),
        UEdGraphSchema_K2::PC_Boolean, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("CurrentSteeringInput"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftYawRate"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);

    UEdGraph* EventGraph = nullptr;
    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (Graph && Graph->GetFName() == TEXT("EventGraph"))
        {
            EventGraph = Graph;
            break;
        }
    }

    if (!EventGraph)
    {
        return Report + TEXT("ERROR=EventGraph missing; ");
    }

    if (HasCommentContaining(EventGraph, TEXT("Codex Mario Kart Drift Runtime Fix")))
    {
        const int32 FixedGuids = EnsureBlueprintNodeGuids(Blueprint);
        return Report + FString::Printf(
            TEXT("RuntimeFix=already_present; NodeGuidsFixed=%d; "),
            FixedGuids);
    }

    UEdGraphNode* TickNode = FindNodeByTitle(EventGraph, TEXT("Event Tick"));
    UEdGraphNode* SteerActionNode = FindNodeByTitle(EventGraph, TEXT("IA_Steer"));
    UEdGraphNode* SetSteeringInputNode =
        FindNodeByTitle(EventGraph, TEXT("Set Steering Input"));

    if (!TickNode || !SteerActionNode || !SetSteeringInputNode)
    {
        return Report + TEXT("ERROR=TickOrSteerNodesMissing; ");
    }

    EventGraph->Modify();
    AddComment(
        EventGraph,
        TEXT("Codex Mario Kart Drift Runtime Fix - tick charge, visible yaw, release boost"),
        3650, -760, 2300, 1050);

    // Remember IA_Steer every time the vehicle movement steering is updated.
    UK2Node_VariableSet* SetCurrentSteering =
        AddVariableSet(EventGraph, TEXT("CurrentSteeringInput"), 950, -40);
    LinkPins(
        FindPinExact(SteerActionNode, TEXT("ActionValue"), EGPD_Output),
        FindVariableInput(SetCurrentSteering, TEXT("CurrentSteeringInput")));
    InsertExecNodeAfter(SetSteeringInputNode, SetCurrentSteering);

    // Continue after the existing tick chain so speed/grounded logic stays intact.
    UEdGraphNode* TickEnd = FindExecChainEnd(TickNode);
    UK2Node_IfThenElse* DriftTickBranch = AddBranch(EventGraph, 3700, -520);
    UK2Node_VariableGet* GetIsDrifting =
        AddVariableGet(EventGraph, TEXT("bIsDrifting"), 3480, -400);
    InsertExecNodeAfter(TickEnd, DriftTickBranch);
    LinkPins(
        FindVariableOutput(GetIsDrifting, TEXT("bIsDrifting")),
        FindPinExact(DriftTickBranch, TEXT("Condition"), EGPD_Input));

    UK2Node_VariableGet* GetDriftCharge =
        AddVariableGet(EventGraph, TEXT("DriftCharge"), 3920, -630);
    UK2Node_VariableGet* GetChargeRate =
        AddVariableGet(EventGraph, TEXT("DriftChargeRate"), 3920, -450);
    UK2Node_CallFunction* DeltaTimesRate = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        4140, -520);
    UK2Node_CallFunction* AddCharge = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Add_DoubleDouble),
        4360, -570);
    UK2Node_VariableSet* SetDriftCharge =
        AddVariableSet(EventGraph, TEXT("DriftCharge"), 4580, -520);

    LinkPins(
        FindPinExact(DriftTickBranch, TEXT("then"), EGPD_Output),
        FindExecIn(SetDriftCharge));
    LinkPins(
        FindPinExact(TickNode, TEXT("DeltaSeconds"), EGPD_Output),
        FindPinExact(DeltaTimesRate, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetChargeRate, TEXT("DriftChargeRate")),
        FindPinExact(DeltaTimesRate, TEXT("B"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetDriftCharge, TEXT("DriftCharge")),
        FindPinExact(AddCharge, TEXT("A"), EGPD_Input));
    LinkPins(
        FindPinExact(DeltaTimesRate, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(AddCharge, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(AddCharge, TEXT("ReturnValue"), EGPD_Output),
        FindVariableInput(SetDriftCharge, TEXT("DriftCharge")));

    // Rotate a little while drifting. Steering controls the sign, so it feels
    // like a Mario Kart powerslide instead of just a boolean state.
    UK2Node_VariableGet* GetCurrentSteer =
        AddVariableGet(EventGraph, TEXT("CurrentSteeringInput"), 4580, -250);
    UK2Node_VariableGet* GetYawRate =
        AddVariableGet(EventGraph, TEXT("DriftYawRate"), 4580, -80);
    UK2Node_CallFunction* SteerTimesYawRate = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        4800, -180);
    UK2Node_CallFunction* YawTimesDelta = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        5020, -180);
    UK2Node_CallFunction* MakeYawRotator = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, MakeRotator),
        5240, -210);
    UK2Node_CallFunction* AddActorLocalRotation = AddCallNode(
        EventGraph,
        AActor::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(AActor, K2_AddActorLocalRotation),
        5460, -520);

    LinkPins(FindThenOut(SetDriftCharge), FindExecIn(AddActorLocalRotation));
    LinkPins(
        FindVariableOutput(GetCurrentSteer, TEXT("CurrentSteeringInput")),
        FindPinExact(SteerTimesYawRate, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetYawRate, TEXT("DriftYawRate")),
        FindPinExact(SteerTimesYawRate, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(SteerTimesYawRate, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(YawTimesDelta, TEXT("A"), EGPD_Input));
    LinkPins(
        FindPinExact(TickNode, TEXT("DeltaSeconds"), EGPD_Output),
        FindPinExact(YawTimesDelta, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(YawTimesDelta, TEXT("ReturnValue"), EGPD_Output),
        FindPinByNameOrCategory(
            MakeYawRotator,
            {TEXT("Yaw"), TEXT("Z (Yaw)")},
            EGPD_Input,
            UEdGraphSchema_K2::PC_Real));
    LinkPins(
        FindPinExact(MakeYawRotator, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(AddActorLocalRotation, TEXT("DeltaRotation"), EGPD_Input));

    // Mark mini-turbo ready from the tick charge, independent of IA_Handbrake
    // TriggeredSeconds.
    UK2Node_VariableGet* GetThreshold =
        AddVariableGet(EventGraph, TEXT("MiniTurboThreshold"), 5020, -720);
    UK2Node_CallFunction* ChargeReadyCompare = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, GreaterEqual_DoubleDouble),
        5240, -720);
    UK2Node_IfThenElse* ReadyBranch = AddBranch(EventGraph, 5680, -520);
    UK2Node_VariableSet* SetReady =
        AddVariableSet(EventGraph, TEXT("bMiniTurboReady"), 5900, -520);
    SetBoolDefault(SetReady, TEXT("bMiniTurboReady"), true);
    UK2Node_CallFunction* PrintReady = AddCallNode(
        EventGraph,
        UKismetSystemLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, PrintString),
        6120, -520);
    SetRealDefault(PrintReady, TEXT("Duration"), TEXT("0.150000"));
    if (UEdGraphPin* InString =
            FindPinExact(PrintReady, TEXT("InString"), EGPD_Input))
    {
        InString->DefaultValue = TEXT("MINI TURBO READY");
    }
    if (UEdGraphPin* Key =
            FindPinExact(PrintReady, TEXT("Key"), EGPD_Input))
    {
        Key->DefaultValue = TEXT("DRIFT");
    }

    LinkPins(FindThenOut(AddActorLocalRotation), FindExecIn(ReadyBranch));
    LinkPins(
        FindVariableOutput(SetDriftCharge, TEXT("Output_Get")),
        FindPinExact(ChargeReadyCompare, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetThreshold, TEXT("MiniTurboThreshold")),
        FindPinExact(ChargeReadyCompare, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(ChargeReadyCompare, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(ReadyBranch, TEXT("Condition"), EGPD_Input));
    LinkPins(
        FindPinExact(ReadyBranch, TEXT("then"), EGPD_Output),
        FindExecIn(SetReady));
    LinkPins(FindThenOut(SetReady), FindExecIn(PrintReady));

    EventGraph->NotifyGraphChanged();
    const int32 FixedGuids = EnsureBlueprintNodeGuids(Blueprint);
    FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    bChanged = true;

    return Report + FString::Printf(
        TEXT("RuntimeFix=created; NodeGuidsFixed=%d; Changed=%s; "),
        FixedGuids,
        bChanged ? TEXT("true") : TEXT("false"));
}

FString UCodexGraphAuditLibrary::FixMarioKartPhysicsDrift()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;
    EnsureMemberVariable(Blueprint, TEXT("CurrentSteeringInput"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);
    EnsureMemberVariable(Blueprint, TEXT("DriftAngularImpulse"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);

    UEdGraph* EventGraph = nullptr;
    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (Graph && Graph->GetFName() == TEXT("EventGraph"))
        {
            EventGraph = Graph;
            break;
        }
    }

    if (!EventGraph)
    {
        return Report + TEXT("ERROR=EventGraph missing; ");
    }

    if (HasCommentContaining(EventGraph, TEXT("Codex Physics Drift")))
    {
        return Report + TEXT("PhysicsDrift=already_present; ");
    }

    UEdGraphNode* OldActorRotation =
        FindNodeByTitle(EventGraph, TEXT("Add Actor Local Rotation"));
    UEdGraphNode* TickNode = FindNodeByTitle(EventGraph, TEXT("Event Tick"));
    if (!OldActorRotation || !TickNode)
    {
        return Report + TEXT("ERROR=OldActorRotationOrTickMissing; ");
    }

    UEdGraphPin* OldExecIn = FindExecIn(OldActorRotation);
    UEdGraphPin* OldThen = FindThenOut(OldActorRotation);
    UEdGraphNode* ChargeSetNode = nullptr;
    UEdGraphNode* ReadyBranchNode = nullptr;
    if (OldExecIn && OldExecIn->LinkedTo.Num() > 0)
    {
        ChargeSetNode = OldExecIn->LinkedTo[0]->GetOwningNode();
    }
    if (OldThen && OldThen->LinkedTo.Num() > 0)
    {
        ReadyBranchNode = OldThen->LinkedTo[0]->GetOwningNode();
    }

    if (!ChargeSetNode || !ReadyBranchNode)
    {
        return Report + TEXT("ERROR=DriftExecChainMissing; ");
    }

    EventGraph->Modify();
    AddComment(
        EventGraph,
        TEXT("Codex Physics Drift - mesh angular impulse, no actor transform move"),
        4520, -30, 1600, 520);

    UK2Node_VariableGet* GetMesh =
        AddVariableGet(EventGraph, TEXT("Mesh"), 4560, 160);
    UK2Node_VariableGet* GetCurrentSteer =
        AddVariableGet(EventGraph, TEXT("CurrentSteeringInput"), 4560, 20);
    UK2Node_VariableGet* GetAngularImpulse =
        AddVariableGet(EventGraph, TEXT("DriftAngularImpulse"), 4560, 250);
    UK2Node_CallFunction* SteerTimesImpulse = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        4780, 70);
    UK2Node_CallFunction* ImpulseTimesDelta = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, Multiply_DoubleDouble),
        5000, 70);
    UK2Node_CallFunction* MakeImpulseVector = AddCallNode(
        EventGraph,
        UKismetMathLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, MakeVector),
        5220, 60);
    UK2Node_CallFunction* AddAngularImpulse = AddCallNode(
        EventGraph,
        UPrimitiveComponent::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, AddAngularImpulseInDegrees),
        5440, 20);

    UEdGraphPin* ChargeThen = FindThenOut(ChargeSetNode);
    if (ChargeThen)
    {
        ChargeThen->BreakAllPinLinks();
        LinkPins(ChargeThen, FindExecIn(AddAngularImpulse));
    }
    if (OldExecIn)
    {
        OldExecIn->BreakAllPinLinks();
    }
    if (OldThen)
    {
        OldThen->BreakAllPinLinks();
    }
    LinkPins(FindThenOut(AddAngularImpulse), FindExecIn(ReadyBranchNode));

    LinkPins(
        FindVariableOutput(GetMesh, TEXT("Mesh")),
        FindPinExact(AddAngularImpulse, TEXT("self"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetCurrentSteer, TEXT("CurrentSteeringInput")),
        FindPinExact(SteerTimesImpulse, TEXT("A"), EGPD_Input));
    LinkPins(
        FindVariableOutput(GetAngularImpulse, TEXT("DriftAngularImpulse")),
        FindPinExact(SteerTimesImpulse, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(SteerTimesImpulse, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(ImpulseTimesDelta, TEXT("A"), EGPD_Input));
    LinkPins(
        FindPinExact(TickNode, TEXT("DeltaSeconds"), EGPD_Output),
        FindPinExact(ImpulseTimesDelta, TEXT("B"), EGPD_Input));
    LinkPins(
        FindPinExact(ImpulseTimesDelta, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(MakeImpulseVector, TEXT("Z"), EGPD_Input));
    LinkPins(
        FindPinExact(MakeImpulseVector, TEXT("ReturnValue"), EGPD_Output),
        FindPinExact(AddAngularImpulse, TEXT("Impulse"), EGPD_Input));
    if (UEdGraphPin* VelChangePin =
            FindPinExact(AddAngularImpulse, TEXT("bVelChange"), EGPD_Input))
    {
        VelChangePin->DefaultValue = TEXT("true");
    }

    EventGraph->NotifyGraphChanged();
    FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    bChanged = true;

    return Report + FString::Printf(
        TEXT("PhysicsDrift=created; DisabledActorLocalRotation=true; Changed=%s; "),
        bChanged ? TEXT("true") : TEXT("false"));
}

FString UCodexGraphAuditLibrary::ConvertDebugHitToControlledRam()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;
    EnsureMemberVariable(Blueprint, TEXT("DebugRamForce"),
        UEdGraphSchema_K2::PC_Real, bChanged, Report);

    UEdGraph* EventGraph = nullptr;
    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (Graph && Graph->GetFName() == TEXT("EventGraph"))
        {
            EventGraph = Graph;
            break;
        }
    }

    if (!EventGraph)
    {
        return Report + TEXT("ERROR=EventGraph missing; ");
    }

    if (HasCommentContaining(EventGraph, TEXT("Codex Debug Ram")))
    {
        return Report + TEXT("DebugRam=already_present; ");
    }

    UEdGraphNode* DebugHitNode =
        FindNodeByTitle(EventGraph, TEXT("IA_DebugHit"));
    UEdGraphNode* OldHitImpulse =
        FindNodeByTitle(EventGraph, TEXT("Apply Hit Impulse"));
    if (!DebugHitNode || !OldHitImpulse)
    {
        return Report + TEXT("ERROR=DebugHitOrApplyHitImpulseMissing; ");
    }

    EventGraph->Modify();
    AddComment(
        EventGraph,
        TEXT("Codex Debug Ram - IA_DebugHit is a controlled forward ram, not a huge hit impulse"),
        620, 720, 1250, 430);

    UK2Node_CallFunction* ApplyRam =
        AddSelfCallNode(EventGraph, TEXT("ApplyForwardBoost"), 700, 880);
    UK2Node_VariableGet* GetDebugRamForce =
        AddVariableGet(EventGraph, TEXT("DebugRamForce"), 700, 1030);
    UK2Node_CallFunction* PrintRam = AddCallNode(
        EventGraph,
        UKismetSystemLibrary::StaticClass(),
        GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, PrintString),
        980, 880);
    SetRealDefault(PrintRam, TEXT("Duration"), TEXT("0.500000"));
    if (UEdGraphPin* InString =
            FindPinExact(PrintRam, TEXT("InString"), EGPD_Input))
    {
        InString->DefaultValue = TEXT("DEBUG RAM");
    }
    if (UEdGraphPin* Key =
            FindPinExact(PrintRam, TEXT("Key"), EGPD_Input))
    {
        Key->DefaultValue = TEXT("DEBUG_RAM");
    }

    if (UEdGraphPin* OldExecIn = FindExecIn(OldHitImpulse))
    {
        OldExecIn->BreakAllPinLinks();
    }
    LinkPins(
        FindPinExact(DebugHitNode, TEXT("Triggered"), EGPD_Output),
        FindExecIn(ApplyRam));
    LinkPins(
        FindVariableOutput(GetDebugRamForce, TEXT("DebugRamForce")),
        FindPinExact(ApplyRam, TEXT("Boost Force"), EGPD_Input));
    LinkPins(FindThenOut(ApplyRam), FindExecIn(PrintRam));

    EventGraph->NotifyGraphChanged();
    FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    bChanged = true;

    return Report + FString::Printf(
        TEXT("DebugRam=created; OldApplyHitImpulseDisconnected=true; Changed=%s; "),
        bChanged ? TEXT("true") : TEXT("false"));
}

FString UCodexGraphAuditLibrary::FixDriftButtonDoesNotBrake()
{
    const TCHAR* VehiclePath =
        TEXT("/Game/DungeonsDash/Actors/Vehicles/BP_DashVehicle.BP_DashVehicle");
    UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, VehiclePath);
    if (!Blueprint)
    {
        return TEXT("ERROR\tBP_DashVehicle failed to load");
    }

    FString Report;
    bool bChanged = false;

    UEdGraph* EventGraph = nullptr;
    for (UEdGraph* Graph : Blueprint->UbergraphPages)
    {
        if (Graph && Graph->GetFName() == TEXT("EventGraph"))
        {
            EventGraph = Graph;
            break;
        }
    }

    if (!EventGraph)
    {
        return TEXT("ERROR=EventGraph missing; ");
    }

    UEdGraphNode* StartedSetHandbrake = nullptr;
    for (UEdGraphNode* Node : EventGraph->Nodes)
    {
        if (!NodeTitleContains(Node, TEXT("Set Handbrake Input")))
        {
            continue;
        }

        UEdGraphPin* bNewHandbrake =
            FindPinExact(Node, TEXT("bNewHandbrake"), EGPD_Input);
        if (bNewHandbrake && bNewHandbrake->LinkedTo.Num() > 0)
        {
            StartedSetHandbrake = Node;
            break;
        }
    }

    if (!StartedSetHandbrake)
    {
        return TEXT("ERROR=StartedSetHandbrakeMissing; ");
    }

    EventGraph->Modify();
    UEdGraphPin* BrakeValuePin =
        FindPinExact(StartedSetHandbrake, TEXT("bNewHandbrake"), EGPD_Input);
    if (BrakeValuePin)
    {
        BrakeValuePin->Modify();
        BrakeValuePin->BreakAllPinLinks();
        BrakeValuePin->DefaultValue = TEXT("false");
        bChanged = true;
        Report += TEXT("StartedHandbrakeForcedFalse=true; ");
    }

    if (!HasCommentContaining(EventGraph, TEXT("Codex Drift Button No Brake")))
    {
        AddComment(
            EventGraph,
            TEXT("Codex Drift Button No Brake - IA_Handbrake starts drift but does not engage Chaos handbrake"),
            1220, -840, 1250, 260);
        bChanged = true;
    }

    if (bChanged)
    {
        EventGraph->NotifyGraphChanged();
        FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
    }

    return Report + FString::Printf(
        TEXT("Changed=%s; "),
        bChanged ? TEXT("true") : TEXT("false"));
}
